[package]
name = "geo-postgis"
version = "0.2.2"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/georust/geo"
documentation = "https://docs.rs/geo-postgis/"
readme = "../README.md"
keywords = ["gis", "geo", "geography", "geospatial", "postgis"]
description = "Conversion between `geo-types` and `postgis` types."
rust-version = "1.65"
edition = "2021"

[dependencies]
postgis = { version = ">=0.7.0, <0.10.0" }
geo-types = { version = "0.7", path = "../geo-types" }
