version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gha-updates:
        applies-to: version-updates
        patterns:
          - "*"
