[package]
name = "geo-test-fixtures"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
wkt = { git = "https://github.com/nyurik/wkt.git", branch = "wkt-dim", optional = true }
geo-types = { path = "../geo-types" }
