[package]
name = "geo-test-fixtures"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
wkt = { version = "0.10.0", default-features = false }
geo-types = "0.7.4"
# Use this after geo-types 0.8+ is published with TZM support
#geo-types = { version = "0.8", path = "../geo-types" }
